[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.19" # Version of solc that we use
optimizer = true        # Enable or disable the solc optimizer
optimizer_runs = 999999 # The number of optimizer runs
verbosity = 3           # The verbosity of tests

remappings = ["forge-std/=lib/forge-std/src/", "@contracts/=contracts/"]
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
goerli = "https://eth-goerli.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
base = "https://mainnet.base.org"
baseGoerli = "https://goerli.base.org"

[etherscan]
baseGoerli = { key = "${BASESCAN_API_KEY}", url = "https://api-goerli.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
